spring:
  config:
    activate:
      on-profile: qa

build:
  version: 2.0

cards:
  message: Welcome to ChiBank cards related QA APIs
  contactDetails:
    name: Natsu - QA Lead
    email: natsu@eazybank.com
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
