spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to ChiBank loans related QA APIs"
  contactDetails:
    name: "Natsu - QA Lead"
    email: "natsu@eazybank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467