build:
  version: 1.0

cards:
  message: Welcome to ChiBank accounts related production APIs
  contactDetails:
    name: Chi - Product Owner
    email: chi@gmail.com
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384