build:
  version: "1.0"

loans:
  message: "Welcome to ChiBank loans related production APIs"
  contactDetails:
    name: "Chi - Product Owner"
    email: "chi@gmail.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956