spring:
  config:
    activate:
      on-profile: prod

build:
  version: 1.0

accounts:
  message: Welcome to ChiBank accounts related production APIs
  contactDetails:
    name: Chi - Product Owner
    email: chi@gmail.com
  onCallSupport:
    - (452) 392-4829
    - (236) 203-0384
