spring:
  config:
    activate:
      on-profile: qa

build:
  version: 2.0

accounts:
  message: Welcome to ChiBank accounts related QA APIs
  contactDetails:
    name: Natsu - QA Lead
    email: natsu@gmail.com
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
