spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///D:/SPRING_BOOT/udemy-MicroServices/demo04 spring cloud config/configserver/src/main/resources/config"
        git:
          uri: "https://github.com/vickyh7518/spring-cloud-configserver-demo.git"
          default-label: main
          timeout: 5 # 配置服務器最多等待 5 秒，超時拋出異常
          clone-on-start: true
          force-pull: true
encrypt:
  key: "5325DBV823TJK99DGF235"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8071